[package]
name = "chat"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = {version = "0.7.4", features=["ws"]}

tokio = { version = "1.36.0", features = ["full"] }
tower-http = { version = "0.5", features = ["fs"]}
futures = "0.3"
